models:
  main_model:
    target: models.diffusion.ldm.LDM
    params:
      conditioning_key: null
      ddpm_config:
        beta: [0.0005, 0.01]
        t_max: 500
        channel: 4
        size: 32
        clip_denoised: True
        sample_img_every_t: 100
        loss_type: l1
        unet_config:
          t_max: 500
          init_channels: 4
          base_channels: 192
          channel_mults: [1, 2, 4]
          use_attention: [1]
          num_res_blocks: 2
          num_groups: 32
          dropout: 0.1
          time_emb_scale: 1.0
          use_t_emb: True
      ae_model:
        target: models.vae.vae.VAE
        ckpt_file: ckpt\vae_s256_32x32x4.pth
        params:
          embed_dim: 4
          coder_config:
            init_channels: 3
            base_channels: 32
            final_channels: 4
            channel_mults: [1, 2, 4, 8]
            use_attention: []
            num_res_blocks: 2
            num_groups: 32
            dropout: 0.1
      condition_model:
        target: null
        ckpt_file: null
        params: null
dataset:
  image_size: 256
  image_channels: 3
  target: datasets.image_dataset.ImageDataset
  params:
    data_dir: E:\datasets\animefaces-konachan
    batch_size: 32
    train_ratio: 0.8
train:
  use_ema: False
  device: cuda:0
  epochs: 300
  base_path: runs
  optimizer:
    target: torch.optim.Adam
    params:
      lr: 0.0005
  scheduler:
    target: torch.optim.lr_scheduler.MultiStepLR
    params:
      milestones: [2, 5, 10, 15, 25, 40]
      gamma: 0.1
