models:
  main_model:
    target: models.vae.vae.VAE
    params:
      embed_dim: 16
      coder_config:
        init_channels: 3
        base_channels: 64
        final_channels: 16
        channel_mults: [1, 2, 4]
        use_attention: [2]
        num_res_blocks: 2
        num_groups: 32
        dropout: 0.1
images:
  image_size: 64
  image_channels: 3
dataset:
  target: datasets.image_dataset.ImageDataset
  params:
    data_dir: E:\datasets\animefaces-konachan
    batch_size: 32
    train_ratio: 0.8
train:
  use_ema: False
  device: cuda:0
  epochs: 200
  lr: 0.0001
  base_path: runs